---
- name: Operating system dependencies
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - libssl-dev
    - libffi-dev
    - python-dev
    - git
    - python-pip
    - python-virtualenv
    - dialog
    - libaugeas0
    - ca-certificates
    - nginx
- name: Python cryptography module
  pip: name=cryptography
- name: Letsencrypt Python client
  git: dest=/opt/certbot clone=yes repo=https://github.com/certbot/certbot force=yes
